name: green-collectives
base: core22
version: '1.0'
summary: Green Collectives - JavaFX Application
description: |
  A Desktop Application built with javaFx with the intention of solving relevant problems and inefficiencies that U.S. Army Service members, and gun enthusiasts face on a daily basis.
confinement: strict

grade: stable

apps:
  green-collectives:
    command: java -jar $SNAP/target/greenSociety-1.0-SNAPSHOT-shaded.jar

    plugs:
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy

parts:
  green-collectives:
    plugin: maven
    source: https://github.com/tcdickson/Green-Collectives.git
    source-type: git
    maven-options:
      - -DskipTests=true
      - -Dsomarg=false