name: green-collectives
base: core18
version: '1.0'
summary: Green Collectives - JavaFX Application
description: |
  A Desktop Application built with javaFx with the intention of solving relevant problems and inefficiencies that U.S. Army Service members, and gun enthusiasts face on a daily basis.

grade: stable
confinement: devmode

apps:
  green-collectives:
    command: $SNAP/usr/lib/jvm/java-11-openjdk-amd64/bin/java -jar $SNAP/green-collectives.jar

    plugs:
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform

parts:
  green-collectives:
    plugin: maven
    source: https://github.com/tcdickson/Green-Collectives.git
    source-type: git
    source-tag: master
    maven-options:
      [ -DskipTests=true, -Dsomarg=false ]
    stage-packages:
      - openjdk-11-jdk
