  name: green-collectives
  base: core18
  version: '1.0'
  summary: Green Collectives - JavaFX Application
  description: |
    A Desktop Application built with javaFx with the intention of solving relevant problems and inefficiencies that U.S. Army Service members, and gun enthusiasts face on a daily basis.

  grade: stable
  confinement: devmode

  apps:
    green-collectives:
      command: run_green_collectives.sh

      plugs:
        - network
        - network-bind
        - home
        - desktop
        - desktop-legacy
      environment:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform

  parts:
    green-collectives:
      plugin: nil
      source: https://github.com/tcdickson/Green-Collectives.git
      source-type: git
      source-tag: master
      stage-packages:
        - openjdk-17-jdk
      organize:
        "run_green_collectives.sh": $SNAPCRAFT_PART_INSTALL/run_green_collectives.sh
        "green-collectives.jar": $SNAPCRAFT_PART_INSTALL/green-collectives.jar
